//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacherFolderManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public int Id { get; set; }
        public Nullable<int> CourseInSOSId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> SemesterNo { get; set; }
        public Nullable<int> TeacherGraderId { get; set; }
    
        public virtual CourseInSOS CourseInSOS { get; set; }
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }
    }
}
