//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacherFolderManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInSOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseInSOS()
        {
            this.Allocation = new HashSet<Allocation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SoSId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> CreditHours { get; set; }
        public Nullable<int> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allocation> Allocation { get; set; }
        public virtual Course Course { get; set; }
        public virtual SchemeOfStudy SchemeOfStudy { get; set; }
    }
}
