//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacherFolderManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderContent
    {
        public int Id { get; set; }
        public Nullable<int> FolderId { get; set; }
        public Nullable<int> FolderCheckListId { get; set; }
        public Nullable<int> FolderSubCheckListId { get; set; }
    
        public virtual Folder Folder { get; set; }
        public virtual FolderCheckList FolderCheckList { get; set; }
    }
}
