//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacherFolderManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderContentDocument
    {
        public int Id { get; set; }
        public int FolderContentId { get; set; }
        public string DisplayName { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> CourseInSOSId { get; set; }
    }
}
