//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacherFolderManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FolderContentDetail
    {
        public int Id { get; set; }
        public Nullable<int> FolderContentId { get; set; }
        public Nullable<int> Marks { get; set; }
        public Nullable<int> QuestionNo { get; set; }
    }
}
