//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacherFolderManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningObjectiveContent
    {
        public int Id { get; set; }
        public Nullable<int> CLOsId { get; set; }
        public Nullable<int> PLOsId { get; set; }
        public Nullable<int> TopicId { get; set; }
        public Nullable<int> Revision { get; set; }
    
        public virtual CLO CLO { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual PLO PLO { get; set; }
        public virtual Session Session { get; set; }
    }
}
