//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacherFolderManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTopicCovered
    {
        public int Id { get; set; }
        public Nullable<int> SubTopicId { get; set; }
        public Nullable<int> AllocationId { get; set; }
        public Nullable<int> WeekNo { get; set; }
        public Nullable<bool> Flag { get; set; }
    }
}
